language: python

python:
    - 2.6
    - 2.7

install:
    - pip install -r requirements.txt --use-mirrors
    - python setup.py install
before_script: mkdir -p shippable/testreports
script: python setup.py test shippable/testreports
